# Generated by Django 5.1.3 on 2024-12-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='backuser',
            fields=[
                ('email', models.EmailField(editable=False, max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
