# Generated by Django 5.1.3 on 2024-12-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veri', '0002_backuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usid',
            field=models.CharField(default='USR200021', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
