# Generated by Django 5.1.3 on 2024-12-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veri', '0004_alter_customuser_usid'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuser',
            name='id',
            field=models.BigAutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backuser',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True),
        ),
    ]
