# Generated by Django 5.1.3 on 2024-12-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veri', '0005_backuser_id_alter_backuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
